export type Permission =
  /* POSTS ROLES */  
  | "POST_CREATE"
  | "POST_UPDATE"
  | "POST_PUBLISH"
  | "POST_ARCHIVE"
  | "USER_CHANGE_ROLE"
  | "USER_CHANGE_PASSWORD"
  | "POST_DRAFT"
  /*USER ROLES */
  | "USER_CREATE"
  | "USER_UPDATE"
  | "USER_CHANGE_STATUS"
  /*AUTHOR ROLES */
  | "AUTHOR_CREATE"
  | "AUTHOR_UPDATE"
  | "AUTHOR_CHANGE_STATUS"
  /*CATEGORY ROLES */
  | "CATEGORY_CREATE"
  | "CATEGORY_UPDATE"